"""add message table

Revision ID: 18ffdff96ab8
Revises: 
Create Date: 2021-05-05 16:25:33.947382

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '18ffdff96ab8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('message',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('author_id', sa.BigInteger(), nullable=False),
    sa.Column('channel_id', sa.BigInteger(), nullable=False),
    sa.Column('guild_id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_message_author_id'), 'message', ['author_id'], unique=False)
    op.create_index(op.f('ix_message_channel_id'), 'message', ['channel_id'], unique=False)
    op.create_index(op.f('ix_message_guild_id'), 'message', ['guild_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_message_guild_id'), table_name='message')
    op.drop_index(op.f('ix_message_channel_id'), table_name='message')
    op.drop_index(op.f('ix_message_author_id'), table_name='message')
    op.drop_table('message')
    # ### end Alembic commands ###
